"""ad add user_name

Revision ID: 15f2c37fa700
Revises: 4fe898f2d1c3
Create Date: 2023-12-16 20:29:36.190815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15f2c37fa700'
down_revision: Union[str, None] = '4fe898f2d1c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads', sa.Column('user_name', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'ads', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'ads', type_='unique')
    op.drop_column('ads', 'user_name')
    # ### end Alembic commands ###
