version: '3.8'

volumes:
  redis_data:

services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - bot

networks:
  bot:
    external: true
